//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 01:14:38 PM IST 
//


package com.qualisystems.pythonDriverPlugin.deployment;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for driverType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="driverType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sources" type="{}sourcesType"/>
 *         &lt;element name="targetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="runFromLocalProject" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="waitForDebugger" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="sourceRootFolder" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "driverType", propOrder = {
    "sources",
    "targetName"
})
public class DriverType {

    @XmlElement(required = true)
    protected SourcesType sources;
    @XmlElement(required = true)
    protected String targetName;
    @XmlAttribute(name = "runFromLocalProject")
    protected Boolean runFromLocalProject;
    @XmlAttribute(name = "waitForDebugger")
    protected Boolean waitForDebugger;
    @XmlAttribute(name = "sourceRootFolder")
    protected String sourceRootFolder;

    /**
     * Gets the value of the sources property.
     * 
     * @return
     *     possible object is
     *     {@link SourcesType }
     *     
     */
    public SourcesType getSources() {
        return sources;
    }

    /**
     * Sets the value of the sources property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourcesType }
     *     
     */
    public void setSources(SourcesType value) {
        this.sources = value;
    }

    /**
     * Gets the value of the targetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * Sets the value of the targetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetName(String value) {
        this.targetName = value;
    }

    /**
     * Gets the value of the runFromLocalProject property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRunFromLocalProject() {
        if (runFromLocalProject == null) {
            return false;
        } else {
            return runFromLocalProject;
        }
    }

    /**
     * Sets the value of the runFromLocalProject property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRunFromLocalProject(Boolean value) {
        this.runFromLocalProject = value;
    }

    /**
     * Gets the value of the waitForDebugger property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isWaitForDebugger() {
        if (waitForDebugger == null) {
            return false;
        } else {
            return waitForDebugger;
        }
    }

    /**
     * Sets the value of the waitForDebugger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWaitForDebugger(Boolean value) {
        this.waitForDebugger = value;
    }

    /**
     * Gets the value of the sourceRootFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceRootFolder() {
        return sourceRootFolder;
    }

    /**
     * Sets the value of the sourceRootFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceRootFolder(String value) {
        this.sourceRootFolder = value;
    }

}
