//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 01:14:38 PM IST 
//


package com.qualisystems.pythonDriverPlugin.deployment;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for propertiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="propertiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serverRootAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="domain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fileFilters" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="waitForDebugger" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="drivers" type="{}driversType"/>
 *         &lt;element name="scripts" type="{}scriptsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "propertiesType", propOrder = {
    "serverRootAddress",
    "port",
    "username",
    "password",
    "domain",
    "fileFilters",
    "waitForDebugger",
    "drivers",
    "scripts"
})
public class PropertiesType {

    @XmlElement(required = true)
    protected String serverRootAddress;
    @XmlElement(required = true)
    protected String port;
    @XmlElement(required = true)
    protected String username;
    @XmlElement(required = true)
    protected String password;
    @XmlElement(required = true)
    protected String domain;
    @XmlElement(required = true)
    protected String fileFilters;
    @XmlElement(required = true)
    protected String waitForDebugger;
    @XmlElement(required = true)
    protected DriversType drivers;
    @XmlElement(required = true)
    protected ScriptsType scripts;

    /**
     * Gets the value of the serverRootAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerRootAddress() {
        return serverRootAddress;
    }

    /**
     * Sets the value of the serverRootAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerRootAddress(String value) {
        this.serverRootAddress = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPort(String value) {
        this.port = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomain(String value) {
        this.domain = value;
    }

    /**
     * Gets the value of the fileFilters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileFilters() {
        return fileFilters;
    }

    /**
     * Sets the value of the fileFilters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileFilters(String value) {
        this.fileFilters = value;
    }

    /**
     * Gets the value of the waitForDebugger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaitForDebugger() {
        return waitForDebugger;
    }

    /**
     * Sets the value of the waitForDebugger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaitForDebugger(String value) {
        this.waitForDebugger = value;
    }

    /**
     * Gets the value of the drivers property.
     * 
     * @return
     *     possible object is
     *     {@link DriversType }
     *     
     */
    public DriversType getDrivers() {
        return drivers;
    }

    /**
     * Sets the value of the drivers property.
     * 
     * @param value
     *     allowed object is
     *     {@link DriversType }
     *     
     */
    public void setDrivers(DriversType value) {
        this.drivers = value;
    }

    /**
     * Gets the value of the scripts property.
     * 
     * @return
     *     possible object is
     *     {@link ScriptsType }
     *     
     */
    public ScriptsType getScripts() {
        return scripts;
    }

    /**
     * Sets the value of the scripts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScriptsType }
     *     
     */
    public void setScripts(ScriptsType value) {
        this.scripts = value;
    }

}
